name = "QiskitIBMRuntimeC"
uuid = "90b98b31-c194-4d1e-bfb5-0d4cb7418088"
authors = ["IBM and its contributors"]
version = "0.1.1"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Qiskit = "91d9a17d-f964-4b6c-a3c4-2f4cfdea2c95"
qiskit_ibm_runtime_jll = "dfd00f80-54b8-5b12-a44d-54bafd549557"

[compat]
julia = "1.10"
Libdl = "1"
Compat = "3.47, 4"
CEnum = "0.5"
Dates = "1"
Qiskit = "~0.4.0"
qiskit_ibm_runtime_jll = "~0.38.0"
Aqua = "0.8.14"
Test = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
